name: Download and Upload AdGuard Filter List

on:
  schedule:
    - cron: '0 0 * * *'
    workflow_dispatch：

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download file
        uses: actions/download-artifact@v3
        with:
          name: adguard-filter-list
          url: https://github.com/ppfeufer/adguard-filter-list/blob/master/blocklist?raw=true

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add adguard-filter-list
          git commit -m "Update adguard-filter-list"
          git push
