name: Download and Upload File

# 定义手动触发和定时触发
on:
  schedule:
    # 每天凌晨 1 点执行一次
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  download_and_upload:
    runs-on: ubuntu-latest

    steps:
    # 检出当前仓库
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 下载指定文件
    - name: Download blocklist file
      run: |
        curl -o blocklist https://github.com/ppfeufer/adguard-filter-list/blob/master/blocklist?raw=true

    # 将下载的文件添加到 git，并提交
    - name: Commit and Push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add blocklist
        git commit -m "Update blocklist file"
        git push
      env:
        # GitHub 提供的默认 token，用于认证
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
